### ISSUE TITLE
Patches with missing or bad info

### ISSUE THREAD

**Issue by Margen67** [xenia-canary/game-patches#117]
The hash may be enough to make sure the patch is being applied to the right version, but there's no way of knowing the exact version of the game the patch is meant for, thus media IDs should be put back.
They were removed in xenia-canary/game-patches@1cd2865b62b2592448beebb5645ce7b11c8a8fa8.

Some games are weird and have `00000000` as the media ID.

Title ID | Serial   | Name                                  | Missing/bad info
-------- | ------   | ----                                  | ----------------
4D5307D1 | MS-2001  | Project Gotham Racing 3               | Missing:<br>`media_id`
4D5307D2 | MS-2002  | Kameo: Elements of Power              | Missing:<br>`media_id`
4D5387E0 | MS-34784 | Kameo: Elements of Power (kiosk demo) | Missing:<br>`media_id`
4D5387E9 | MS-34793 | Kameo: Elements of Power (demo)       | Missing:<br>`media_id`
4D530910 | MS-2320  | Forza Motorsport 4                    | Missing:<br>`media_id`
58410B00 | XA-2816  | Dead Rising 2 Case West               | Missing:<br>`hash`
434307D4 | CC-2004  | Resident Evil 5                       | Missing:<br>`hash` module filename
445007EA | DP-2026  | Onechanbara                           | Missing:<br>`hash` module filename<br>`media_id`
454107D9 | EA-2009  | Need for Speed: Most Wanted (2005)    | Missing:<br>`media_id`
454107EC | EA-2028  | Need for Speed: Carbon                | Missing:<br>`hash` module filename<br>`media_id`
465307D6 | FS-2006  | Armored Core 4                        | Missing:<br>`hash`<br>`media_id`
545107FC | TQ-2044  | Saints Row 2                          | Missing:<br>`hash` module filename
545407DF | TT-2015  | Rockstar Table Tennis                 | Missing:<br>`hash`<br>`media_id`
584108DB | XA-2267  | A Kingdom for Keflings                | Missing:<br>`hash` module filename
584109FF | XA-2559  | Plants vs. Zombies                    | Missing:<br>`hash` module filename
4541087F | EA-2175  | Skate 2                               | Missing:<br>`media_id`
5553088C | US-2188  | Far Cry 3                             | Missing:<br>`hash` module filename<br>Bad:<br>`hash`
5841124F | XA-4687  | Doritos Crash Course 2                | Missing:<br>`media_id`
41560904 | AV-2308  | Transformers: Rise of The Dark Spark  | Missing:<br>`hash`
43430830 | CC-2096  | Lost Planet 3                         | Missing:<br>`hash`
43430841 | CC-2113  | Resident Evil                         | Missing:<br>`hash` module filename
43430842 | CC-2114  | Resident Evil 0                       | Missing:<br>`hash` module filename
45410806 | EA-2054  | Burnout Paradise (1.00)               | Missing:<br>`hash`<br>`media_id`
45410806 | EA-2054  | Burnout Paradise (Screenshot)         | Missing:<br>`media_id`
45410914 | EA-2324  | Rock Band 3                           | Missing:<br>`hash` module filename<br>`media_id`
53450812 | SE-2066  | Sonic Unleashed (TU2)                 | Bad:<br>`hash`
53450812 | SE-2066  | Sonic Unleashed                       | Missing:<br>`media_id`
53510806 | SQ-2054  | Final Fantasy XIII-2                  | Missing:<br>`hash` module filename<br>`media_id`
57520802 | WR-2050  | Batman: Arkham City (TU6)             | Missing:<br>`hash`<br>`hash` module filename<br>`media_id`
57520802 | WR-2050  | Batman: Arkham City                   | Missing:<br>`media_id`
57520828 | WR-2088  | Batman: Arkham Origins                | Missing:<br>`hash`<br>`hash` module filename<br>`media_id`
57520828 | WR-2088  | Batman: Arkham Origins (TU3)          | Missing:<br>`media_id`

**Comment by bomabomaboma** [comment]
[https://github.com/xenia-canary/game-patches/pull/155](url)
The list needs to have changed reflected from the above PR.

Module names no longer needed for:
Transformers-Rise of The Dark Spark
Lost Planet 3
Burnout Paradise 1.00
Armored Core 4
Rockstar Table Tennis
DEADRISING 2 CASE WEST

**Comment by bomabomaboma** [comment]
**State of Decay (TU 5)** is also missing a module name. 

Was previously `default.xex(?)` but has been changed to `TODO: Add module filename`

**Comment by Margen67** [comment]
This is covered by our linting now.
