### ISSUE TITLE
Most games with 60 FPS patches have double-buffered vsync

### ISSUE THREAD

**Issue by GavinKeane** [xenia-canary/game-patches#148]
This patch works very well in areas that are not very graphically busy.

However, in areas that are graphically busy, the game reverts to a 30fps cap. I could be wrong but I think this is not a performance issue on my end. I believe the game is programmed specifically to behave like this. I say this because the shift in fps goes from 60 (steady without drops) instantly to 30 (also steady without drops) depending on the busyness of the scene.

I really appreciate the work you folks do here. I wish I could figure it out myself with ghidra, but I lack the skills.

I've attached a video so you can see what I mean. The fps is being displayed in the top left corner.

https://user-images.githubusercontent.com/32646750/171295512-b136ddcb-a368-457c-bfdd-6b97acf09d07.mp4

**Comment by illusion0001** [comment]
Fault of double buffer vsync, it can only flip up to 2 frames at a time if the budget does not meet it's rendering time.

**Comment by GavinKeane** [comment]
Do you think this could be resolved then, either by modifying xenia config or the nvidia control panel?

**Comment by Margen67** [comment]
> Fault of double buffer vsync, it can only flip up to 2 frames at a time if the budget does not meet it's rendering time.

This also applies to most other 60FPS patched games.

**Comment by Margen67** [comment]
This might be caused by Xenia's vsync.

**Comment by Margen67** [comment]
Games with vsync options:
  * Lego Indiana Jones 2
  * Saints Row 2

**Comment by bomabomaboma** [comment]
@Margen67 I don't think this issue should be open here anymore. The 360 does not have native triple-buffering support so patching device-init/DX9 functions isn't a means of circumventing this specific issue, therefore it's outside the purview of #game-patches and perhaps a problem with the emulator itself.

What do you think?

**Comment by Margen67** [comment]
> @Margen67 I don't think this issue should be open here anymore. The 360 does not have native triple-buffering support so patching device-init/DX9 functions isn't a means of circumventing this specific issue, therefore it's outside the purview of #game-patches and perhaps a problem with the emulator itself.
> 
> What do you think?

Some games have tearing on real hardware so I think this is a Xenia issue.
