### ISSUE TITLE
(58410954.patch) Banjo Kazooie 60fps makes in-game timers count down at double the speed

### ISSUE THREAD

**Issue by xmat123x** [xenia-canary/game-patches#2]
I'm playing through the game and the 60fps patch is practically perfect aside from timers counting down at double the speed making some challenges significantly harder and others like the ring trial in Clanker's Cavern impossible.

**Comment by illusion0001** [comment]
Patching isn't perfect, there's more issues noted here https://github.com/xenia-canary/game-patches/commit/4253636767b661330c010b3a7fcd0f8de12418b3#commitcomment-45178043

**Comment by oSerenity** [comment]
this should be closed

**Comment by illusion0001** [comment]
PR #47 is for Tooie, not Kazooie, this will remain opened.

**Comment by retrobenny** [comment]
My recent changes got pushed for PR #52 which has the fix for that timer issue for all incidents,so now this issue can be closed.
Just make sure to set every single patch code for the fixes to true as I didn't want to take the risk of it becoming unstable if I made it all one massive code.

**Comment by illusion0001** [comment]
Resolved in https://github.com/xenia-canary/game-patches/pull/52
