### ISSUE TITLE
Patches wont load no matter what i try

### ISSUE THREAD

**Issue by HacubeMehh** [xenia-canary/game-patches#20]
i cant get patches to load at all

**Comment by illusion0001** [comment]
Have you read the [install](https://github.com/xenia-canary/game-patches#installing) guide

**Comment by HacubeMehh** [comment]
> Have you read the [install](https://github.com/xenia-canary/game-patches#installing) guide

i have

**Comment by bomabomaboma** [comment]
@HacubeMehh please join the Xenia discord and ask for help there. This is not the appropriate venue for troubleshooting.

Thanks.
