### ISSUE TITLE
Small audio issues on red dead

### ISSUE THREAD

**Issue by K119w** [xenia-canary/game-patches#228]
Red dead
There is an audio big where every time when galloping on horse alone there low tone audio cracking synced to the horse steps only when galloping but nothing else even when your driving a wagon there is nothing

**Comment by Margen67** [comment]
Does this happen on master?

**Comment by K119w** [comment]
> 

I dont use masters but i tried it it still present but on master the gameplay experience is not the best because the frames are well below 20fps so i use canary. On canary the gameplay is very smooth and no bugs at all is just this small audio bug and over longtime galloping on horse back it gets irritating. Thanks

**Comment by K119w** [comment]
> Does this happen on master?

Update this is not only happening in red dead its also in an other game nfs prostreet. It’s seems there is an issue with the low tone audio cues they always come with this audio crack

**Comment by K119w** [comment]
> Does this happen on master?

I would like to add that when i play both of this game for the first time there was not any of these issues but after launching them for the second the audio cracks started to appear so it could be some config settings that are causing these I tried playing with vsync and anti aliasing  and sharpening settings but I noticed every time I turned them off these audio cracks appear in a lower tone amd less frequent so

**Comment by K119w** [comment]
Not solved

**Comment by K119w** [comment]
.
