### ISSUE TITLE
Create 4D530AA4 - Forza Horizon 2.patch.toml

### ISSUE THREAD

**Issue by Mutantovich** [xenia-canary/game-patches#237]
title_name = "Forza Horizon 2"
title_id = "4D530AA4" # MS-2724
#media_id = "4000D145" # Disc (USA): http://redump.org/disc/60608/

[[patch]]
name = "Disable Motion Blur"
author = "me"
is_enabled = true

[[patch.be32]]
address = 0x92F04494
value = 0x60000000

[[patch]]
name = "Disable Depth of Field"
author = "me"
is_enabled = true

[[patch.be32]]
address = 0x9243B2E4
value = 0x39600000
[[patch.be32]]
address = 0x924382BC
value = 0x39600000
[[patch.be32]]
address = 0x924382EC
value = 0x39600000

**Comment by Margen67** [comment]
?

**Comment by Mutantovich** [comment]
Why not?

**Comment by Margen67** [comment]
This isn't how you submit pull requests.

**Comment by Mutantovich** [comment]
I've already messed up two pull requests, sorry for my incompetence. I just
want you to add a patch in any way you like. I can't really delve into the
technical aspects, please forgive me again. I'm not really worried about
all that formal stuff and authorship. Forza gamers need it anyway.

чт, 9 мар. 2023 г., 21:17 Margen67 ***@***.***>:

**Comment by Margen67** [comment]
#262
