### ISSUE TITLE
Can't get [applyed patches] to pop up on load?

### ISSUE THREAD

**Issue by Diamonda101** [xenia-canary/game-patches#255]
![image](https://github.com/xenia-canary/game-patches/assets/76970218/e2140dc2-c0f5-4706-b84b-7b10115927d4)
this pops up in xenia logs

for the configs its set to true for patches 
and i have the patches folder 
i made sure everthing matched 
![image](https://github.com/xenia-canary/game-patches/assets/76970218/1183c396-f5df-4de4-a6e9-e6a2da8278dd)
this is what my folder look like

**Comment by Margen67** [comment]
Post the log file
