### ISSUE TITLE
Patch Request - Sonic & Sega All-Stars Racing 

### ISSUE THREAD

**Issue by MightyMacT** [xenia-canary/game-patches#279]
Sonic & Sega All-Stars Racing has insanely bright bloom effects on every track. Some tracks are bearable such as "Whale Lagoon", but other tracks with lots of snow such as "Icicle Valley" make the game unplayable as shown below. This was played on a vanilla Xenia with in-game brightness turned to 0%. Disabling "draw_resolution_scaled_texture_offsets" also had no effect.

![Desktop Screenshot 2024 01 15 - 01 40 08 27](https://github.com/xenia-canary/game-patches/assets/156659526/08df96d9-b71b-4056-aa0b-aa947206410d)
![Desktop Screenshot 2024 01 15 - 01 40 39 75](https://github.com/xenia-canary/game-patches/assets/156659526/b4372513-1d35-4ee1-b481-9f8dbb9ddedf)
![Desktop Screenshot 2024 01 15 - 01 38 50 84](https://github.com/xenia-canary/game-patches/assets/156659526/6ecba928-7c95-49cc-bb2b-1d51b110d9b1)
![Desktop Screenshot 2024 01 15 - 01 39 01 77](https://github.com/xenia-canary/game-patches/assets/156659526/6875d2dd-505a-4ebe-b1c8-208696b28d20)

**Comment by illusion0001** [comment]
Turn on read back resolve

**Comment by MightyMacT** [comment]
@illusion0001 Thanks! This worked! Here's the results:

![Desktop Screenshot 2024 01 16 - 14 05 40 23](https://github.com/xenia-canary/game-patches/assets/156659526/a9f63b9c-b880-4cd8-bd40-8e1c827ee765)
