### ISSUE TITLE
Grand Theft Auto IV - Add .xex plugin support

### ISSUE THREAD

**Issue by nvzut** [xenia-canary/game-patches#298]
Just like for Grand Theft Auto V (TU27), Grand Theft Auto IV could have plugin support using writable_code_segments.

I was trying to do this myself, but have little coding experience. Looking at the patch @AdrianCassar made for Grand Theft Auto V (TU27) didn't make me any wiser as to how this is done.

**Comment by AdrianCassar** [comment]
Plugin support was added to canary as a feature therefore manually injecting plugins is no longer required. I have documented the usage of plugin support [here](https://github.com/AdrianCassar/game-patches/blob/plugin_docs/.github/Plugin-Docs.md#xenia-canary-game-plugins).

**Comment by nvzut** [comment]
That’s perfect. I wasn’t able to find the page you linked before. Thank you for your reply and all your great work!
