### ISSUE TITLE
Sonic Generations textures fix

### ISSUE THREAD

**Issue by LuizP2** [xenia-canary/game-patches#330]
Can we get some fix for this?
![53450848 - 2024-09-19T16-18-02](https://github.com/user-attachments/assets/16ac8c2d-4c77-49df-a5c9-6e05432f5823)
![53450848 - 2024-09-19T16-17-57](https://github.com/user-attachments/assets/52348dcf-e75c-4a9c-acf2-211be0b18bde)
![53450848 - 2024-09-19T16-12-50](https://github.com/user-attachments/assets/4c5587e6-d75c-4b2c-bda5-c63e6171f1d8)

idk if it is a problem of the rom that im using or it is of the emulator, but im getting the same result on both versions of Xenia Canary (PC and Xbox One Dev Mode)

**Comment by Margen67** [comment]
Not possible to fix with patches. It needs to be fixed on Xenia's side.
