### ISSUE TITLE
Patches with missing hashes

### ISSUE THREAD

**Issue by Margen67** [xenia-canary/game-patches#66]
* [x] [4D530A26 - Gears of War Judgment](https://github.com/xenia-canary/game-patches/blob/main/patches/4D530A26%20-%20Gears%20of%20War%20Judgment.patch#L1-L3)
* [x] [4D530A87 - Fable Anniversary](https://github.com/xenia-canary/game-patches/blob/main/patches/4D530A87%20-%20Fable%20Anniversary.patch#L1-L3)
* [x] [4D5307D1 - PGR3](https://github.com/xenia-canary/game-patches/blob/main/patches/4D5307D1%20-%20PGR3.patch#L1-L3)
* [x] [4D5307DF - Blue Dragon](https://github.com/xenia-canary/game-patches/blob/main/patches/4D5307DF%20-%20Blue%20Dragon.patch#L1-L3)
* [x] [4D5307F1 - Fable II (GOTY_Platinum Edition, TU1)](https://github.com/xenia-canary/game-patches/blob/main/patches/4D5307F1%20-%20Fable%20II%20(GOTY_Platinum%20Edition%2C%20TU1).patch#L1-L3)
* [x] [4D5308AB - Gears of War 3](https://github.com/xenia-canary/game-patches/blob/main/patches/4D5308AB%20-%20Gears%20of%20War%203.patch#L1-L3)
* [x] [4D5309C9 - Forza Horizon](https://github.com/xenia-canary/game-patches/blob/main/patches/4D5309C9%20-%20Forza%20Horizon.patch#L1-L3)
* [x] [4D53082D - Gears of War 2](https://github.com/xenia-canary/game-patches/blob/main/patches/4D53082D%20-%20Gears%20of%20War%202.patch#L1-L3)
* [x] [434D0822 - Leisure Suit Larry](https://github.com/xenia-canary/game-patches/blob/main/patches/434D0822%20-%20Leisure%20Suit%20Larry.patch#L1-L3)
* [x] [454107D9 - NFS Most Wanted 2005](https://github.com/xenia-canary/game-patches/blob/main/patches/454107D9%20-%20NFS%20Most%20Wanted%202005.patch#L1-L3)
* [x] [454108E6 - Skate 3](https://github.com/xenia-canary/game-patches/blob/main/patches/454108E6%20-%20Skate%203.patch#L1-L3)
* [x] [535107E4 - Final Fantasy 13](https://github.com/xenia-canary/game-patches/blob/main/patches/535107E4%20-%20Final%20Fantasy%2013.patch#L1-L3)
* [x] [535107E8 - NIER](https://github.com/xenia-canary/game-patches/blob/main/patches/535107E8%20-%20NIER.patch#L1-L3)
* [x] [535107FA - Deus Ex Human Revolution](https://github.com/xenia-canary/game-patches/blob/main/patches/535107FA%20-%20Deus%20Ex%20Human%20Revolution.patch#L1-L3)
* [x] [545107D1 - Saints Row (TU1)](https://github.com/xenia-canary/game-patches/blob/main/patches/545107D1%20-%20Saints%20Row%20(TU1).patch#L1-L3)
* [x] [545407DF](https://github.com/xenia-canary/game-patches/blob/main/patches/545407DF%20-%20Rockstar%20Table%20Tennis.patch#L1-L3)
* [x] ~~[584108A9 - GoldenEye 007](https://github.com/xenia-canary/game-patches/blob/main/patches/584108A9%20-%20GoldenEye%20007.patch#L1-L3)~~ Release was altered, requires multiple hashes
* [x] [584111E8 - State of Decay (TU5)](https://github.com/xenia-canary/game-patches/blob/main/patches/584111E8%20-%20State%20of%20Decay%20(TU5).patch#L1-L3)
* [x] [584111F7 - Minecraft (XBLA, TU0)](https://github.com/xenia-canary/game-patches/blob/main/patches/584111F7%20-%20Minecraft%20(XBLA%2C%20TU0).patch#L1-L3)
* [x] [5343080B - Batman Arkham Asylum GOTY](https://github.com/xenia-canary/game-patches/blob/main/patches/5343080B%20-%20Batman%20Arkham%20Asylum%20GOTY.patch#L1-L3)
* [x] [5454085D - Bioshock Infinite](https://github.com/xenia-canary/game-patches/blob/main/patches/5454085D%20-%20Bioshock%20Infinite.patch#L1-L3)
* [x] [5841096A - Hydro Thunder Hurricane](https://github.com/xenia-canary/game-patches/blob/main/patches/5841096A%20-%20Hydro%20Thunder%20Hurricane.patch#L1-L3)
* [x] [53510806 - Final Fantasy 13-2](https://github.com/xenia-canary/game-patches/blob/main/patches/53510806%20-%20Final%20Fantasy%2013-2.patch#L1-L3)
* [x] [53518810 - Final Fantasy 13-2 Demo](https://github.com/xenia-canary/game-patches/blob/main/patches/53518810%20-%20Final%20Fantasy%2013-2%20Demo.patch#L1-L3)
* [x] [54510866 - WWE All Stars](https://github.com/xenia-canary/game-patches/blob/main/patches/54510866%20-%20WWE%20All%20Stars.patch#L1-L3)
* [x] #73
* [x] [57520828 - Batman Arkham Origins (TU3)](https://github.com/xenia-canary/game-patches/blob/main/patches/57520828%20-%20Batman%20Arkham%20Origins%20(TU3).patch#L1-L3)
* [x] [58410954 - Banjo Kazooie](https://github.com/xenia-canary/game-patches/blob/main/patches/58410954%20-%20Banjo%20Kazooie.patch#L1-L3)
* [x] [58410955 - Banjo Tooie](https://github.com/xenia-canary/game-patches/blob/main/patches/58410955%20-%20Banjo%20Tooie.patch#L1-L3)

**Comment by illusion0001** [comment]
I knew this would happen one day
